name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9.7
  - pip=23.0.1
  - cudatoolkit=11.3
  - pytorch=1.13.1
  - torchvision=0.14.1
  - numpy=1.23.5
  - albumentations
  - diffusers
  - opencv-python
  - pudb
  - invisible-watermark
  - imageio
  - imageio-ffmpeg
  - pytorch-lightning
  - omegaconf
  - test-tube
  - streamlit
  - einops
  - torch-fidelity
  - transformers
  - torchmetrics
  - kornia
  - taming-transformers @ git+https://github.com/CompVis/taming-transformers.git@master
  - clip @ git+https://github.com/openai/CLIP.git@main
